### ISSUE TITLE
Fatal error: write EPIPE

### ISSUE THREAD

**Issue by oYo-fr** [oncletom/grunt-crx#55]
I have the folowing error (I'm including the entire trace here for your convience, error is at the end) :

 
$ node.exe C:\Users\Yoann\AppData\Roaming\npm\node_modules\grunt-cli\bin\grunt --gruntfile "C:\Users\Yoann\Google Drive\Projets\JobSpot\client\Gruntfile.js" --verbose crx:production
Initializing
Command-line options: --gruntfile=C:\Users\Yoann\Google Drive\Projets\JobSpot\client\Gruntfile.js, --verbose

Reading "Gruntfile.js" Gruntfile...OK

Registering Gruntfile tasks.

Registering "grunt-angular-gettext" local Npm module tasks.
Reading C:\Users\Yoann\Google Drive\Projets\JobSpot\client\node_modules\grunt-angular-gettext\package.json...OK
Parsing C:\Users\Yoann\Google Drive\Projets\JobSpot\client\node_modules\grunt-angular-gettext\package.json...OK
Loading "compile.js" tasks...OK
+ nggettext_compile
Loading "extract.js" tasks...OK
+ nggettext_extract

Registering "grunt-autoprefixer" local Npm module tasks.
Reading C:\Users\Yoann\Google Drive\Projets\JobSpot\client\node_modules\grunt-autoprefixer\package.json...OK
Parsing C:\Users\Yoann\Google Drive\Projets\JobSpot\client\node_modules\grunt-autoprefixer\package.json...OK
Loading "autoprefixer.js" tasks...OK
+ autoprefixer

Registering "grunt-concurrent" local Npm module tasks.
Reading C:\Users\Yoann\Google Drive\Projets\JobSpot\client\node_modules\grunt-concurrent\package.json...OK
Parsing C:\Users\Yoann\Google Drive\Projets\JobSpot\client\node_modules\grunt-concurrent\package.json...OK
Loading "concurrent.js" tasks...OK
+ concurrent

Registering "grunt-contrib-clean" local Npm module tasks.
Reading C:\Users\Yoann\Google Drive\Projets\JobSpot\client\node_modules\grunt-contrib-clean\package.json...OK
Parsing C:\Users\Yoann\Google Drive\Projets\JobSpot\client\node_modules\grunt-contrib-clean\package.json...OK
Loading "clean.js" tasks...OK
+ clean

Registering "grunt-contrib-concat" local Npm module tasks.
Reading C:\Users\Yoann\Google Drive\Projets\JobSpot\client\node_modules\grunt-contrib-concat\package.json...OK
Parsing C:\Users\Yoann\Google Drive\Projets\JobSpot\client\node_modules\grunt-contrib-concat\package.json...OK
Loading "concat.js" tasks...OK
+ concat

Registering "grunt-contrib-connect" local Npm module tasks.
Reading C:\Users\Yoann\Google Drive\Projets\JobSpot\client\node_modules\grunt-contrib-connect\package.json...OK
Parsing C:\Users\Yoann\Google Drive\Projets\JobSpot\client\node_modules\grunt-contrib-connect\package.json...OK
Loading "connect.js" tasks...OK
+ connect

Registering "grunt-contrib-copy" local Npm module tasks.
Reading C:\Users\Yoann\Google Drive\Projets\JobSpot\client\node_modules\grunt-contrib-copy\package.json...OK
Parsing C:\Users\Yoann\Google Drive\Projets\JobSpot\client\node_modules\grunt-contrib-copy\package.json...OK
Loading "copy.js" tasks...OK
+ copy

Registering "grunt-contrib-cssmin" local Npm module tasks.
Reading C:\Users\Yoann\Google Drive\Projets\JobSpot\client\node_modules\grunt-contrib-cssmin\package.json...OK
Parsing C:\Users\Yoann\Google Drive\Projets\JobSpot\client\node_modules\grunt-contrib-cssmin\package.json...OK
Loading "cssmin.js" tasks...OK
+ cssmin

Registering "grunt-contrib-htmlmin" local Npm module tasks.
Reading C:\Users\Yoann\Google Drive\Projets\JobSpot\client\node_modules\grunt-contrib-htmlmin\package.json...OK
Parsing C:\Users\Yoann\Google Drive\Projets\JobSpot\client\node_modules\grunt-contrib-htmlmin\package.json...OK
Loading "htmlmin.js" tasks...OK
+ htmlmin

Registering "grunt-contrib-imagemin" local Npm module tasks.
Reading C:\Users\Yoann\Google Drive\Projets\JobSpot\client\node_modules\grunt-contrib-imagemin\package.json...OK
Parsing C:\Users\Yoann\Google Drive\Projets\JobSpot\client\node_modules\grunt-contrib-imagemin\package.json...OK
Loading "imagemin.js" tasks...OK
+ imagemin

Registering "grunt-contrib-jshint" local Npm module tasks.
Reading C:\Users\Yoann\Google Drive\Projets\JobSpot\client\node_modules\grunt-contrib-jshint\package.json...OK
Parsing C:\Users\Yoann\Google Drive\Projets\JobSpot\client\node_modules\grunt-contrib-jshint\package.json...OK
Loading "jshint.js" tasks...OK
+ jshint

Registering "grunt-contrib-nodeunit" local Npm module tasks.
Reading C:\Users\Yoann\Google Drive\Projets\JobSpot\client\node_modules\grunt-contrib-nodeunit\package.json...OK
Parsing C:\Users\Yoann\Google Drive\Projets\JobSpot\client\node_modules\grunt-contrib-nodeunit\package.json...OK
Loading "nodeunit.js" tasks...OK
+ nodeunit

Registering "grunt-contrib-uglify" local Npm module tasks.
Reading C:\Users\Yoann\Google Drive\Projets\JobSpot\client\node_modules\grunt-contrib-uglify\package.json...OK
Parsing C:\Users\Yoann\Google Drive\Projets\JobSpot\client\node_modules\grunt-contrib-uglify\package.json...OK
Loading "uglify.js" tasks...OK
+ uglify

Registering "grunt-contrib-watch" local Npm module tasks.
Reading C:\Users\Yoann\Google Drive\Projets\JobSpot\client\node_modules\grunt-contrib-watch\package.json...OK
Parsing C:\Users\Yoann\Google Drive\Projets\JobSpot\client\node_modules\grunt-contrib-watch\package.json...OK
Loading "watch.js" tasks...OK
+ watch

Registering "grunt-cordova-ng" local Npm module tasks.
Reading C:\Users\Yoann\Google Drive\Projets\JobSpot\client\node_modules\grunt-cordova-ng\package.json...OK
Parsing C:\Users\Yoann\Google Drive\Projets\JobSpot\client\node_modules\grunt-cordova-ng\package.json...OK
Loading "cordova.js" tasks...OK
+ cordova

Registering "grunt-crx" local Npm module tasks.
Reading C:\Users\Yoann\Google Drive\Projets\JobSpot\client\node_modules\grunt-crx\package.json...OK
Parsing C:\Users\Yoann\Google Drive\Projets\JobSpot\client\node_modules\grunt-crx\package.json...OK
Loading "crx.js" tasks...OK
+ crx

Registering "grunt-filerev" local Npm module tasks.
Reading C:\Users\Yoann\Google Drive\Projets\JobSpot\client\node_modules\grunt-filerev\package.json...OK
Parsing C:\Users\Yoann\Google Drive\Projets\JobSpot\client\node_modules\grunt-filerev\package.json...OK
Loading "filerev.js" tasks...OK
+ filerev

Registering "grunt-google-cdn" local Npm module tasks.
Reading C:\Users\Yoann\Google Drive\Projets\JobSpot\client\node_modules\grunt-google-cdn\package.json...OK
Parsing C:\Users\Yoann\Google Drive\Projets\JobSpot\client\node_modules\grunt-google-cdn\package.json...OK
Loading "cdnify.js" tasks...OK
+ cdnify

Registering "grunt-includes" local Npm module tasks.
Reading C:\Users\Yoann\Google Drive\Projets\JobSpot\client\node_modules\grunt-includes\package.json...OK
Parsing C:\Users\Yoann\Google Drive\Projets\JobSpot\client\node_modules\grunt-includes\package.json...OK
Loading "includes.js" tasks...OK
+ includes

Registering "grunt-newer" local Npm module tasks.
Reading C:\Users\Yoann\Google Drive\Projets\JobSpot\client\node_modules\grunt-newer\package.json...OK
Parsing C:\Users\Yoann\Google Drive\Projets\JobSpot\client\node_modules\grunt-newer\package.json...OK
Loading "newer.js" tasks...OK
+ any-newer, newer, newer-clean, newer-postrun

Registering "grunt-ng-annotate" local Npm module tasks.
Reading C:\Users\Yoann\Google Drive\Projets\JobSpot\client\node_modules\grunt-ng-annotate\package.json...OK
Parsing C:\Users\Yoann\Google Drive\Projets\JobSpot\client\node_modules\grunt-ng-annotate\package.json...OK
Loading "ng-annotate.js" tasks...OK
+ ngAnnotate

Registering "grunt-svgmin" local Npm module tasks.
Reading C:\Users\Yoann\Google Drive\Projets\JobSpot\client\node_modules\grunt-svgmin\package.json...OK
Parsing C:\Users\Yoann\Google Drive\Projets\JobSpot\client\node_modules\grunt-svgmin\package.json...OK
Loading "svgmin.js" tasks...OK
+ svgmin

Registering "grunt-usemin" local Npm module tasks.
Reading C:\Users\Yoann\Google Drive\Projets\JobSpot\client\node_modules\grunt-usemin\package.json...OK
Parsing C:\Users\Yoann\Google Drive\Projets\JobSpot\client\node_modules\grunt-usemin\package.json...OK
Loading "usemin.js" tasks...OK
+ usemin, useminPrepare

Registering "grunt-wiredep" local Npm module tasks.
Reading C:\Users\Yoann\Google Drive\Projets\JobSpot\client\node_modules\grunt-wiredep\package.json...OK
Parsing C:\Users\Yoann\Google Drive\Projets\JobSpot\client\node_modules\grunt-wiredep\package.json...OK
Loading "wiredep.js" tasks...OK
+ wiredep
Reading package.json...OK
Parsing package.json...OK
Reading crx/manifest.json...OK
Parsing crx/manifest.json...OK
Initializing config...OK

Registering "grunt-angular-gettext" local Npm module tasks.
Reading C:\Users\Yoann\Google Drive\Projets\JobSpot\client\node_modules\grunt-angular-gettext\package.json...OK
Parsing C:\Users\Yoann\Google Drive\Projets\JobSpot\client\node_modules\grunt-angular-gettext\package.json...OK
Loading "compile.js" tasks...OK
+ nggettext_compile
Loading "extract.js" tasks...OK
+ nggettext_extract

Registering "grunt-cordova-ng" local Npm module tasks.
Reading C:\Users\Yoann\Google Drive\Projets\JobSpot\client\node_modules\grunt-cordova-ng\package.json...OK
Parsing C:\Users\Yoann\Google Drive\Projets\JobSpot\client\node_modules\grunt-cordova-ng\package.json...OK
Loading "cordova.js" tasks...OK
+ cordova

Registering "grunt-contrib-jshint" local Npm module tasks.
Reading C:\Users\Yoann\Google Drive\Projets\JobSpot\client\node_modules\grunt-contrib-jshint\package.json...OK
Parsing C:\Users\Yoann\Google Drive\Projets\JobSpot\client\node_modules\grunt-contrib-jshint\package.json...OK
Loading "jshint.js" tasks...OK
+ jshint

Registering "grunt-contrib-concat" local Npm module tasks.
Reading C:\Users\Yoann\Google Drive\Projets\JobSpot\client\node_modules\grunt-contrib-concat\package.json...OK
Parsing C:\Users\Yoann\Google Drive\Projets\JobSpot\client\node_modules\grunt-contrib-concat\package.json...OK
Loading "concat.js" tasks...OK
+ concat

Registering "grunt-includes" local Npm module tasks.
Reading C:\Users\Yoann\Google Drive\Projets\JobSpot\client\node_modules\grunt-includes\package.json...OK
Parsing C:\Users\Yoann\Google Drive\Projets\JobSpot\client\node_modules\grunt-includes\package.json...OK
Loading "includes.js" tasks...OK
+ includes

Registering "grunt-crx" local Npm module tasks.
Reading C:\Users\Yoann\Google Drive\Projets\JobSpot\client\node_modules\grunt-crx\package.json...OK
Parsing C:\Users\Yoann\Google Drive\Projets\JobSpot\client\node_modules\grunt-crx\package.json...OK
Loading "crx.js" tasks...OK
+ crx
Loading "Gruntfile.js" tasks...OK
+ build, default, serve, server, test

Running tasks: crx:production

Running "crx:production" (crx) task
Verifying property crx.production exists in config...OK
Files: www -> crx/dist/happyatwork-0.1-dev.crx
Reading C:\Users\Yoann\Google Drive\Projets\JobSpot\client\node_modules\grunt-crx\lib/../data/config-default.json...OK
Parsing C:\Users\Yoann\Google Drive\Projets\JobSpot\client\node_modules\grunt-crx\lib/../data/config-default.json...OK
Reading crx/crx.pem...OK
Reading www\manifest.json...OK
Parsing www\manifest.json...OK
Reading package.json...OK
Parsing package.json...OK
Fatal error: write EPIPE

Execution Time (2015-05-12 22:35:32 UTC)
loading tasks    17ms  █████ 11%
crx:production  142ms  █████████████████████████████████████████ 89%
Total 160ms

Process finished with exit code 3

I tried reinstalling my packages with no success

**Comment by oYo-fr** [comment]
with the --stack option :

Fatal error: write EPIPE
Error: write EPIPE
    at exports._errnoException (util.js:746:11)
    at Socket._writeGeneric (net.js:690:26)
    at Socket._write (net.js:709:8)
    at doWrite (_stream_writable.js:301:12)
    at writeOrBuffer (_stream_writable.js:288:5)
    at Socket.Writable.write (_stream_writable.js:217:11)
    at Socket.write (net.js:634:40)
    at Socket.Writable.end (_stream_writable.js:449:10)
    at Socket.end (net.js:415:31)
    at generatePublicKey (C:\Users\Yoann\Google Drive\Projets\JobSpot\client\node_modules\grunt-crx\node_modules\crx\src\crx.js:95:15)

**Comment by oYo-fr** [comment]
Error occurs on my windows machine, not on my mac...
OpenSSL configuration error ?

**Comment by szujak** [comment]
You can try using http://www.cygwin.com/ instead of default windows console

**Comment by oncletom** [comment]
Could try by generating the key directly with `crx`, it would be ace, and helpful to understand if the problem lies in `grunt-crx` or `crx` itself.

I will either maintain this issue or close it down in favour of one in the oncletom/crx repo.

Thanks :-)

**Comment by paulutkin** [comment]
I have following error.

Running "clean:dist" (clean) task
>> 0 paths cleaned.

Running "concurrent:pre" (concurrent) task

    Running "ngconstant:app" (ngconstant) task
    Creating module obefiveApp.constants at client/app/app.constant.js...OK

    Done, without errors.


    Execution Time (2016-08-22 19:48:45 UTC+3)
    loading tasks              353ms  █████████████████████████████ 82%
    loading grunt-ng-constant   56ms  █████ 13%
    ngconstant:app              21ms  ██ 5%
    Total 430ms

Running "concurrent:dist" (concurrent) task

    Running "imagemin:dist" (imagemin) task
    Fatal error: write EPIPE


    Execution Time (2016-08-22 19:48:46 UTC+3)
    loading tasks                   404ms  ██████████████ 44%
    loading grunt-contrib-imagemin  468ms  ████████████████ 50%
    imagemin:dist                    56ms  ██ 6%
    Total 928ms
Warning:  Use --force to continue.

Aborted due to warnings.


Execution Time (2016-08-22 19:48:44 UTC+3)
loading tasks                363ms  █████████████████ 11%
loading grunt-contrib-clean   35ms  ██ 1%
loading grunt-concurrent      58ms  ███ 2%
concurrent:pre                1.1s  ████████████████████████████████████████████████████ 35%
concurrent:dist               1.6s  ████████████████████████████████████████████████████████████████████████████ 51%
Total 3.2s

**Comment by oncletom** [comment]
Let me know if you still encounter this issue with `grunt-crx@1.0.4` :-)
